###

# curl -X POST http://localhost:5000/api/stockfish
#-H 'Content-Type: application/json'
#-d '{"fen": "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1", "level": 10, "query_type": "best_move"}'
POST http://localhost:5000/api/stockfish
Content-Type: application/json

{
  "fen": "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
  "level": 10,
  "query_type": "wdl"
}

###

